### ISSUE TITLE
No internet connection after connecting to the WireGuard tunnel

### ISSUE THREAD

**Issue by freerko** [Mawthuq-Software/wireguard-manager-and-api#10]
Hi,

I've set up wireguard-manager-and-api via Docker and created keys like this on a different machine:

> root@server ~ # wg genkey | tee private.key | wg pubkey > public.key
root@server ~ # cat private.key
iBjbKpaS5MKLE0umMciE7kQD0u3fBm5LD8L2rRe02VY=
root@server ~ # cat public.key
8KbN4MeEflQS1nX3J6Ts1Piq19ohjNHnQcjXs94yF0g=
root@server ~ # wg genpsk
QanbVcZd2gWMyiHZU3pTO8V5vmQplLCaenvYM8cBdqM=

Then I called the API like this:
> root@server ~ # curl --request POST   --url http://1.2.3.4:8443/manager/key   --header 'Content-Type: application/json'   --data '{
    "publicKey": "8KbN4MeEflQS1nX3J6Ts1Piq19ohjNHnQcjXs94yF0g=",
    "presharedKey": "QanbVcZd2gWMyiHZU3pTO8V5vmQplLCaenvYM8cBdqM=",
    "bwLimit": 1000,
    "subExpiry": "2022-Mar-31 12:39:05 PM",
    "ipIndex": 0
}'
{"allowedIPs":"0.0.0.0/0, ::0","dns":"1.1.1.1","ipAddress":"1.2.3.4","ipv4Address":"10.8.0.10/32","ipv6Address":"fe22:22:22::10/128","keyID":"1","listenPort":"443","publicKey":"T2Rs6GA5d9Wcxa5TysQahaF6O/GRWvliUNv7BvxVsx0=","response":"Added key successfully"}root@server ~ #

and created a wireguard.conf like this:

>[Interface]
PrivateKey = iBjbKpaS5MKLE0umMciE7kQD0u3fBm5LD8L2rRe02VY=
Address = 10.8.0.10/32
DNS = 1.1.1.1
>
>[Peer]
PublicKey = T2Rs6GA5d9Wcxa5TysQahaF6O/GRWvliUNv7BvxVsx0=
PresharedKey = QanbVcZd2gWMyiHZU3pTO8V5vmQplLCaenvYM8cBdqM=
Endpoint = 1.2.3.4:443
AllowedIPs = 0.0.0.0/0,::/0

On the client I can activate the connection and the status is "active" (green) afterwards and I can see in the WireGuard client that I send data to the tunnel. On the server I `docker exec -t -i container_name /bin/bash` and look at the WireGuard status:

> docker@37c9107db68a:/usr/src/wireguard-manager-and-api$ sudo wg show
interface: wg0
  public key: T2Rs6GA5d9Wcxa5TysQahaF6O/GRWvliUNv7BvxVsx0=
  private key: (hidden)
  listening port: 443
>
>peer: 8KbN4MeEflQS1nX3J6Ts1Piq19ohjNHnQcjXs94yF0g=
  preshared key: (hidden)
  allowed ips: 10.8.0.10/32, fe22:22:22::10/128

So no handshakes visible and the peer line is yellow. On the client I can't connect to the Internet. How can I debug this further? Do I have to do `sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE` for the docker interface or for the host eth0 interface? Do I have to set `net.ipv4.ip_forward=1` in the sysctl.conf on the host? Is my wireguard.conf correct for the keys generated?

**Comment by RaspberryTech01** [comment]
Hi, could you check the port you have selected is open in your server firewall? Also in the docker-compose file I noticed that its 51820:51820

You need to shutdown the old docker container and edit that to 443:443.

Furthermore, can you check your client end to see if anything is being sent/received in bytes? If just a few bytes are sent at a time (around 148-200bytes) that means your server is not allowing in a connection. If many bytes are going in but few are coming out, that means your server is not allowing bytes out due to dns or firewall issues.

**Comment by freerko** [comment]
Now it works, thanks! I didn't notice I not only have to change the port in the `/opt/wgManagerAPI/config.json` but as well in the `docker-compose.yml`.

**Comment by RaspberryTech01** [comment]
No worries, ill add that to the documentation.
