### ISSUE TITLE
[FEATURE] Include a local DNS server (e.g. unbound) in the docker file

### ISSUE THREAD

**Issue by freerko** [Mawthuq-Software/wireguard-manager-and-api#11]
**Is your feature request related to a problem? Please describe.**
Currently by default, users have to set INSTANCE.IP.GLOBAL.DNS to a public DNS server like 1.1.1.1 or 8.8.8.8 so that wireguard-manager-and-api can provide it to the end users to include in their wireguard.conf. But for anonymity purposes it is not ideal to use such a public DNS server, it would be better to be able to resolve domains locally.

**Describe the solution you'd like**
It would be great to have a local DNS server (for example unbound) created along the WireGuard service.
I've found a basic setup of unbound for WireGuard here: https://gist.github.com/Anachron/e2ba7ace4e4ef6988182adc7462ffb80

**Describe alternatives you've considered**
Sorry, didn't try to include unbound setup in the docker file myself, yet.

**Comment by RaspberryTech01** [comment]
I am not super familiar with how unbound works but dont you need an upstream provider? The `INSTANCE.IP.GLOBAL.DNS` is what sets the clients DNS, i.e when adding a key, this DNS value is sent back in the JSON response. 

[https://github.com/notasausage/pi-hole-unbound-wireguard](https://github.com/notasausage/pi-hole-unbound-wireguard) in this project, they use a `192.168.x.x` IP Address with pihole and unbound. I am not sure if that means you need to be on the same local network, but probably not.
