### ISSUE TITLE
[FEATURE] Add SAML Auth

### ISSUE THREAD

**Issue by yarons** [Mawthuq-Software/wireguard-manager-and-api#15]
**Is your feature request related to a problem? Please describe.**
The authentication is much easier when working with GitHub/GitLab/Okta/etc,

**Describe the solution you'd like**
Allow exchanging keys with any SAML IdP.

**Describe alternatives you've considered**
Adding usernames and passwords for everyone.

**Additional context**
[SAML on Wikipedia](https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language)

**Comment by RaspberryTech01** [comment]
Thank you very much for your feature issue. Whilst this would be a great future to implement, currently we are building the basics up with a username password system. 

In the future, we may implement such user authentication systems for the business version.

**Comment by RaspberryTech01** [comment]
Closing as currently the project has no funding. May add this as a feature in the future.
