### ISSUE TITLE
[FEATURE] Client-side option when running the container

### ISSUE THREAD

**Issue by RiwanBodereau** [Mawthuq-Software/wireguard-manager-and-api#5]
Hello,

**Is your feature request related to a problem? Please describe.**
Connecting automatically wireguard client to the server using the API.

**Describe the solution you'd like**
A container running as "client" which can generate public/private key and PSK, requesting the server (API) and starting wireguard based on the response.
This could be useful for auto-provisionning of wireguard clients.
Use case : server templates which can connect to the wireguard server automatically on boot.

**Describe alternatives you've considered**
I've been trying to use this : https://github.com/perara/wg-manager
It basically does the same thing and has a client option when running the container, but i've been unable to make it work.

I'll probably make a simple dockerfile that works in bash, but wondering if you could add this or if this was planned.

Thanks in advance,

Regards,

**Comment by RaspberryTech01** [comment]
@RiwanBodereau Hi Riwan, sorry did not see this issue until now. I don't fully understand what you mean exactly. Do you mean the client computer has a script which runs this application which you want me to make to automatically add a wireguard key and enable it?

Currently we are working on a front-end or this project.. It will take a while. 
If you want, you can make the script with the API calls to the location.

**Comment by RaspberryTech01** [comment]
No response.
