### ISSUE TITLE
404 Error while calling api vai postman

### ISSUE THREAD

**Issue by priteshuae** [Mawthuq-Software/wireguard-manager-and-api#6]
trying to call Api vai postman, everything looks good but throwing of error 404 not Found.

I am not using lets encrypt .
can you make detailed guide to use this i am not experienced. with api .

**Comment by RaspberryTech01** [comment]
Hi @priteshuae, sorry for the late reply, I didn't see this issue until now.

Make sure when calling the API you are using the correct path. The paths are in the README with what to use (i.e, POST/GET) and also the path to the api call you want to make (i.e http://yourserverorIp:8443/manager/something)

**Comment by RaspberryTech01** [comment]
No response after 3 months.
