### ISSUE TITLE
[FEATURE] Creating publicKey/presharedKey via this API?

### ISSUE THREAD

**Issue by freerko** [Mawthuq-Software/wireguard-manager-and-api#7]
Hi,

as far as I understood this project, it allows me to roll out *existing* publicKeys and presharedKeys to (potentially many) VPN nodes, correct? I am looking for a solution that takes care of the `wg genkey` and `wg genpsk` part of the user setup as well, so an API that I can call to create the keys and giving me the complete connection details in return. Would this be possible with your project? I especially like the Expiry feature!

**Comment by RaspberryTech01** [comment]
Hi, 

Yes it allows you to roll out existing keys so long you have a private key. Preshared keys can be regenerated and sent if needed.

In terms of generating the keys through the API, we wont be implementing that as that is not secure.

That being said, I am going to be releasing a basic front end website/gui which allows you to connect to multiple of these backends. The front end can generate the keys for you. (But again there is no API as its all local) 

Edit: GUI is out.
