### ISSUE TITLE
[BUG] Disabling IPv6 doesn't work

### ISSUE THREAD

**Issue by freerko** [Mawthuq-Software/wireguard-manager-and-api#9]
Hi,

I try to set up wireguard-manager-and-api via Docker. Since IPv6 is not yet supported via Docker, I've tried to set INSTANCE.IP.LOCAL.IPV6.ADDRESS to "-" and INSTANCE.IP.LOCAL.IPV6.ENABLED to "false" as advised in the documentation. When starting the container without a database, it tries to populate the database with many entries where each ips.ipv6_address is set to "-" which failes because of the UNIQUE contraint, resulting in only the first IPv4 address written to the database correctly:

>root@server:~# docker-compose up
Starting root_wireguard-manager-and-api_1 ... done
Attaching to root_wireguard-manager-and-api_1
wireguard-manager-and-api_1  | WG MANAGER AND API STARTING UP
wireguard-manager-and-api_1  | Env file loading - 1/6
wireguard-manager-and-api_1  | Logger starting up - 2/6
wireguard-manager-and-api_1  | Starting database - 3/6
wireguard-manager-and-api_1  |
wireguard-manager-and-api_1  | 2022/03/30 19:31:00 /usr/src/wireguard-manager-and-api/src/db/db.go:95 record not found
wireguard-manager-and-api_1  | [0.115ms] [rows:0] SELECT * FROM `ips` WHERE ipv4_address = "10.8..0.108" ORDER BY `ips`.`ipv4_address` LIMIT 1
wireguard-manager-and-api_1  |
wireguard-manager-and-api_1  | 2022/03/30 19:31:00 /usr/src/wireguard-manager-and-api/src/db/db.go:108 UNIQUE constraint failed: ips.ipv6_address
wireguard-manager-and-api_1  | [0.120ms] [rows:0] INSERT INTO `ips` (`ipv4_address`,`ipv6_address`,`in_use`,`wg_interface`) VALUES ("10.8.0.4","-","false","wg0")
wireguard-manager-and-api_1  |
wireguard-manager-and-api_1  | 2022/03/30 19:31:00 /usr/src/wireguard-manager-and-api/src/db/db.go:108 UNIQUE constraint failed: ips.ipv6_address
wireguard-manager-and-api_1  | [0.087ms] [rows:0] INSERT INTO `ips` (`ipv4_address`,`ipv6_address`,`in_use`,`wg_interface`) VALUES ("10.8.0.5","-","false","wg0")
...

The same happens when I keep INSTANCE.IP.LOCAL.IPV6.ENABLED as "false" but set INSTANCE.IP.LOCAL.IPV6.ADDRESS to "fe22:22:22::3". It populates the database as intended when I set INSTANCE.IP.LOCAL.IPV6.ENABLED to "true".

**Comment by RaspberryTech01** [comment]
Thank you for reporting this, ill check it out shortly. 

It seems that in the tableStructs:
```go
type IP struct {
	IPv4Address string `gorm:"primaryKey"`
	IPv6Address string `gorm:"unique"`
	InUse       string
	WGInterface string
}
```

the IPv6 address is unique.
For your IPV6 local, can you try setting it? It seems the ipv6 must always be set at least locally for it the application to work. IPv6 GLOBAL, just leave as an empty array.

Here is my config which works with docker:
```json
{
  "INSTANCE": {
    "IP": {
      "LOCAL": {
        "IPV4": {
          "ADDRESS" : "10.6.0.1",
          "SUBNET": "/16"
        },
        "IPV6": {
          "ADDRESS": "fe22:22:22::3",
          "SUBNET": "/64",
          "ENABLED": true
        }
      },
      "GLOBAL": {
        "DNS": "1.1.1.1",
        "ADDRESS": {
          "IPV4": [
                "REDACTED", "REDACTED"
          ],
          "IPV6": [
          ]
        },
        "ALLOWED": "0.0.0.0/0, ::/0"
      }
    },
    "PORT": 51821
  },
```

**Comment by RaspberryTech01** [comment]
updated documentation in the deploy branch (gitlab), ipv6 local address must be set for the application to work. global ipv6 array can be left empty.
